### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by mcranford13** [mcranford13/Ps2Plus#4]
I'm currently designing a pcb that can be ordered and then populated with this mcu. Should be ready to go in a few days. Will be pushed to the hardware section.

**Comment by Gameboypi** [comment]
will do you think the PIC16(L)F18856/76 40-pin UQFN (5x5) will work insted of the big one?
if it's I designed a pcb for it.
let me know if it's gonna work i will send you the files
thanks for sharing this!!
![2](https://user-images.githubusercontent.com/41389319/62265880-9acafb80-b42e-11e9-9481-b9590e99d05f.png)
![1](https://user-images.githubusercontent.com/41389319/62265881-9acafb80-b42e-11e9-8fdc-25c25c6a1ba5.png)

**Comment by mcranford13** [comment]
Almost done with this. Just need to make it a little bit more streamlined for portables. Should be released later today.

**Comment by mcranford13** [comment]
PCB Design is complete although not optimal.
